language: php
dist: trusty
php:
  - 7.0
  - 7.1
  - nightly
  - hhvm
services:
  - mongodb
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - sudo apt-get install -y libdmtx-utils
  - composer install --prefer-dist --dev --no-interaction
  # Get fresh tests
  - rm -rf vendor/maslosoft/mangantest
  - git clone https://github.com/Maslosoft/ManganTest.git vendor/maslosoft/mangantest
  # Ensure that test script is executable
  - chmod +x run-travis
before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "extension=mongo.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
script:
  - cd $TRAVIS_BUILD_DIR
  - bash run-travis
