language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
services:
  - mongodb
install:
  - composer install
before_script:
# Wait for mongodb
  - sleep 15
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
script: phpunit --coverage-clover=coverage.clover