language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
services:
  - mongodb
install:
  - composer install
before_script:
# Wait for mongodb
  - sleep 15
  - phpenv config-add travis.ini
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.clover
script: vendor/codeception/codeception/codecept --colors --coverage-xml=coverage.clover --coverage-html=. run
#script: phpunit --coverage-clover=coverage.clover --bootstrap vendor/maslosoft/mangantest/bootstrap.php vendor/maslosoft/mangantest/tests