language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
services:
  - mongodb
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - sudo apt-get install -y libdmtx-utils
  - rm composer.lock
  - composer require "ptachoire/php-dmtx:^1"
  # Required for php 5
  - composer update
  - composer install --prefer-dist --dev --no-interaction
  # Ensure that test script is executable
  - chmod +x run-travis
before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "extension=mongo.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
script:
  - cd $TRAVIS_BUILD_DIR
  - bash run-travis
