language: php
php:
  - 5.6
  - 5.5
  - nightly
  - hhvm
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 505A7412
  - echo "deb [arch=amd64] http://s3.amazonaws.com/tokumx-debs $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/tokumx.list
  - sudo apt-get update
  - sudo apt-get install -y tokumx
  - sudo apt-get install -y dmtx-utils
install:
  - composer install --prefer-dist --dev --no-interaction
  - pushd vendor/maslosoft/mangantest && git reset --hard && git pull && popd
before_script:
# Wait for mongodb
  - sleep 5
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "extension=mongo.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
script:
  - run-travis
