language: php
dist: trusty
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
services:
  - mongodb
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
cache:
  directories:
    - vendor
install:
  - pecl install mongodb
  - sudo apt-get install -y libdmtx-utils
  - composer require "ptachoire/php-dmtx:^1"
  - composer install --prefer-dist --dev --no-interaction
  # Ensure that test script is executable
  - chmod +x run-travis
script:
  - cd $TRAVIS_BUILD_DIR
  - bash run-travis
