language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
before_install:
  - wget https://repo.percona.com/apt/percona-release_0.1-3.$(lsb_release -sc)_all.deb
  - sudo dpkg -i percona-release_0.1-3.$(lsb_release -sc)_all.deb
  - sudo apt-get update
  - sudo apt-get install -y percona-server-mongodb
  - sudo service mongod stop
  - sudo rm -rf /var/lib/mongodb/*
  - sudo sed -i '/engine: \*PerconaFT/s/#//g' /etc/mongod.conf
  - sudo service mongod start
install:
  - composer install --prefer-dist --dev --no-interaction
  - composer update
before_script:
# Wait for mongodb
  - sleep 5
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "extension=mongo.so\n" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
script:
  - run-travis
