#!/bin/bash

touch ./toc/CHANGELOG.md
touch ./toc/INSTALL.md
touch ./toc/README.md
touch ./toc/UPGRADE.md

generate-md --layout ./toc --input ./toc --output .
cp ./toc/README.md ./README.md
cp ./toc/CHANGELOG.md ./CHANGELOG.md
